### PR TITLE
Dev/rename pluginstub

### PR DESCRIPTION
**Pull request by cannam**
For discussion. What do you think?

### CODE REVIEW

**Comment by cannam** [comment]
Just realised I didn't update the unit tests! The problem is that the unit tests don't depend on anything in the Makefile, so they don't automatically get rebuilt. In fact the Makefile has various problems, which I might open an issue for.

**Comment by LucasThompson** [comment]
> For discussion. What do you think?

I generally agree, not much to say without immediately getting into bike shed territory. i.e. essentially using the library name, or repeating namespaces, as prefixes in type names (basically the use of Piper). Perhaps something like piper_vamp::client::AdapterPlugin contains all the information. However, adapter already has its own meaning in the Vamp domain, so scrap that.

I am just nitpicking for the sake of it - I don't feel the above is a better suggestion. I think PiperVampPlugin conveys exactly what it is. 

PiperAutoPlugin isn't so clear. I also noticed some of the more detailed comments you added the other day aren't here. From the comments _'This "plugin" makes the Piper client abstraction behave like a local Vamp plugin'_, sounds like a PiperVampPlugin to me. I understand that it has _"its own server that lasts only for the lifetime of this plugin"_, hence "Auto". PiperVampAutoPlugin? or perhaps PiperPlugin and PiperAutoPlugin? piper_vamp::client::Plugin and piper_vamp::client::AutoPlugin?

Naming is hard and I think your suggestions are fine.

> Just realised I didn't update the unit tests! The problem is that the unit tests don't depend on anything in the Makefile, so they don't automatically get rebuilt.

Ah, I hadn't realised that - at least the continuous integration acts as a safety net here.

**Comment by cannam** [comment]
On Thu, 9 Feb 2017, at 14:00, Lucas Thompson wrote:
> I also noticed some of the more detailed
> comments you added the other day aren't here.

Blimey, you're right -- where did they go I wonder?

> PiperVampAutoPlugin? or perhaps PiperPlugin and PiperAutoPlugin?

I also wondered about putting something server-related in there.
PiperServerOwningPlugin. PiperServerManagerFactoryMonitorPluginAdapter.

**Review by LucasThompson — APPROVED** [review]
Good stuff, method names are certainly better like this. Naming the plugins is hard, I do like PiperVampPlugin more than PiperStub.

**Pull request merged**
